// Code generated by sqlc. DO NOT EDIT.

package crud_sqlc

import (
	"database/sql"
	"time"
)

type Good struct {
	ID          int32          `json:"id"`
	ProjectID   int32          `json:"project_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Priority    int32          `json:"priority"`
	Removed     bool           `json:"removed"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Project struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
